# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sapid', models.CharField(max_length=18)),
                ('hostname', models.CharField(max_length=14)),
                ('loopback', models.CharField(max_length=15)),
                ('mac', models.CharField(max_length=17)),
            ],
        ),
    ]
